GET http://localhost:8080/item?name=hi
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200, it is ${response.status}");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received ${response.contentType.mimeType}");
  // client.assert(response.body.hasOwnProperty("name"), `Expected to have property name but did not.`);
  // client.assert(response.body["name"] === "josh", `Expected to have name josh but instead have ${response.body['name']}.`);
});
%}

### Successful test: check response status is 200
GET https://httpbin.org/status/200

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###
# curl -X GET --location "http://localhost:8080/item?name=hi"
#    -H "Accept: application/json"
GET http://localhost:8080/item?name=hi
Accept: application/json

###

