# Start with a UBI, install and run postgres
# Build up the DDL and make sure nothing breaks.
# Note: this test is a functional one and depends on the quality
# and scale of test data to detect an issue.
